-- =====
-- Module : cadence / virtuoso / ICADVM_20.10.340
-- Generated by: gen_module.py 2025-09-15 05:17:45
-- Author: Lin-Hung Lai
-- =====

-- =======================================================
-- Tool / Module Identifiers
-- =======================================================
local version     = "ICADVM_20.10.340"
local tool        = "IC"        -- cad_root vendor/tool path
local module_name = "virtuoso"      -- exposed module name (folder under module_root)
local vendor      = "cadence"
local MODULE      = string.upper(module_name)
-- =======================================================

-- =======================================================
-- Define common variables
-- =======================================================
local cad_root  = "${CAD_ROOT}"
local bins = {
  "tools/dfII/bin",
  "tools/dfII/bin/64bit",
  "tools/dracula/bin",
  "tools/dracula/bin/64bit",
  "tools/bin",
  "tools/bin/64bit",
}
local libs = {
  "tools/lib",
  "tools/lib/64bit",
  "tools/Qt/v5/64bit/lib",
  "tools/Qt/v5/64bit/lib/64bit",
  "tools.lnx86/sev/lib/64bit",
  "tools.lnx86/TPtools/grpc-3.12.2/lib64",
  "tools.lnx86/TPtools/grpc-3.12.2/lib",
  "oa_v22.60.091/lib/linux_rhel60_64/opt/",
}
local manuals = {

}

-- Tool install root under CAD
local root = cad_root .. "/" .. vendor .. "/" .. tool .. "/" .. version

-- =======================================================
-- Module file
-- =======================================================
help([[ ]] .. MODULE .. [[ ]] .. version .. [[ (]] .. string.upper(vendor) .. [[)]])
whatis("Vendor       : " .. string.upper(vendor))
whatis("Module       : " .. MODULE)
whatis("Tool path    : " .. tool)
whatis("Version      : " .. version)
whatis("===========================")
whatis("Original author: Lin-Hung Lai")
whatis("Date: 12 Sep 2025")
whatis("===========================")

-- ========= Dependencies =========
depends_on("site")
depends_on("license/all")

-- ========= PATH =========
for _,p in ipairs(bins) do
  local full = pathJoin(root, p)
  if (isDir(full)) then
    prepend_path("PATH", full)
  end
end

-- ========= Libraries =========
for _,p in ipairs(libs) do
  local full = pathJoin(root, p)
  if (isDir(full)) then
    prepend_path("LD_LIBRARY_PATH", full)
    prepend_path("SHLIB_PATH",      full)
  end
end

-- ========= MANPATH =========
for _,p in ipairs(manuals) do
  local full = pathJoin(root, p)
  if (isDir(full)) then
    prepend_path("MANPATH", full)
  end
end

-- ========= Extra LD paths (cad_root-relative) =========


-- ========= Environment Variables =========
setenv("CADENCE", cad_root .. "/cadence")
setenv("CDSHOME", root)
setenv("CDS_AUTO_64BIT", "ALL")

-- ========= Aliases =========


-- ========= Load Message =========
local map = {
  synopsys = "1;35",  -- 粗體 + 紫色
  cadence  = "1;33",  -- 粗體 + 黃色
  mentor   = "1;34",  -- 粗體 + 藍色
}
local function colored(txt, code)
  -- 若不想要顏色（TERM=dumb 或 LMOD_COLORIZE=no），就回傳純文字
  local t = (os.getenv("TERM") or "")
  local lc = (os.getenv("LMOD_COLORIZE") or "yes"):lower()
  if t == "dumb" or lc == "no" then return txt end
  return string.format("\27[%sm%s\27[0m", code, txt)
end
local code = map[string.lower(vendor)] or "1;32"  -- 預設粗體綠色
local module_name_colored = colored(module_name, code)
local version_colored = colored(version, code)  -- 粗體黃色
if (mode() == "load") then
  local bar = string.rep("=", 72)
  LmodMessage(bar)
  LmodMessage(string.format("[MOD] Loaded %s tool: %s/%s", vendor, module_name_colored, version_colored))
  LmodMessage("Provider : ".. colored("Lin-Hung Lai", "33") .. " @ " .. colored("v1.0.1", "33") .. " - " .. colored("12 Sep 2025", "33"))  -- 36=cyan, 35=purple
  LmodMessage("Platform : ".. colored("Rocky Linux 8.10", "33"))
  LmodMessage(bar)
end

