help([[Visual Studio Code (Lab) - Shared Extensions]])
whatis("Name: code-lab")
whatis("Version: 2025.12.19")
whatis("Category: Editor, IDE")
whatis("Description: VS Code with lab-shared extensions and lab defaults")
prepend_path("PATH", "/usr/local/bin")
set_alias("code", "/usr/local/bin/code-lab")
set_alias("code-lab", "/usr/local/bin/code-lab")
setenv("VSCODE_DISABLE_TELEMETRY", "1")
setenv("ELECTRON_DISABLE_SECURITY_WARNINGS", "true")
