-- =====
-- Module : mentor / calibre / 2025.3_28.17
-- Generated by: gen_module.py 2025-09-15 05:21:48
-- Author: Lin-Hung Lai
-- =====

-- =======================================================
-- Tool / Module Identifiers
-- =======================================================
local version     = "2025.3_28.17"
local tool        = "calibre"        -- cad_root vendor/tool path
local module_name = "calibre"      -- exposed module name (folder under module_root)
local vendor      = "mentor"
local MODULE      = string.upper(module_name)
-- =======================================================

-- =======================================================
-- Define common variables
-- =======================================================
local cad_root  = "${CAD_ROOT}"
local bins = {
  "bin",
}
local libs = {

}
local manuals = {

}

-- Tool install root under CAD
local root = cad_root .. "/" .. vendor .. "/" .. tool .. "/" .. version

-- =======================================================
-- Module file
-- =======================================================
help([[ ]] .. MODULE .. [[ ]] .. version .. [[ (]] .. string.upper(vendor) .. [[)]])
whatis("Vendor       : " .. string.upper(vendor))
whatis("Module       : " .. MODULE)
whatis("Tool path    : " .. tool)
whatis("Version      : " .. version)
whatis("===========================")
whatis("Original author: Lin-Hung Lai")
whatis("Date: 12 Sep 2025")
whatis("===========================")

-- ========= Dependencies =========
depends_on("license/all")
depends_on("site")

-- ========= PATH =========
for _,p in ipairs(bins) do
  local full = pathJoin(root, p)
  if (isDir(full)) then
    prepend_path("PATH", full)
  end
end

-- ========= Libraries =========
for _,p in ipairs(libs) do
  local full = pathJoin(root, p)
  if (isDir(full)) then
    prepend_path("LD_LIBRARY_PATH", full)
    prepend_path("SHLIB_PATH",      full)
  end
end

-- ========= MANPATH =========
for _,p in ipairs(manuals) do
  local full = pathJoin(root, p)
  if (isDir(full)) then
    prepend_path("MANPATH", full)
  end
end

-- ========= Extra LD paths (cad_root-relative) =========


-- ========= Environment Variables =========
setenv("MGC_HOME", root)
setenv("CALIBRE_HOME", root)
setenv("MGC_TMPDIR", "/tmp")
setenv("MGC_LOCATION_MAP", "NO_MAP")
setenv("CALIBRE_2025_1_ENABLE_DEPRECATED_RHEL7", "3")
setenv("CALIBRE_2025_2_ENABLE_DEPRECATED_RHEL7", "6")

-- ========= Aliases =========


-- ========= Load Message =========
local map = {
  synopsys = "1;35",  -- 粗體 + 紫色
  cadence  = "1;33",  -- 粗體 + 黃色
  mentor   = "1;34",  -- 粗體 + 藍色
}
local function colored(txt, code)
  -- 若不想要顏色（TERM=dumb 或 LMOD_COLORIZE=no），就回傳純文字
  local t = (os.getenv("TERM") or "")
  local lc = (os.getenv("LMOD_COLORIZE") or "yes"):lower()
  if t == "dumb" or lc == "no" then return txt end
  return string.format("\27[%sm%s\27[0m", code, txt)
end
local code = map[string.lower(vendor)] or "1;32"  -- 預設粗體綠色
local module_name_colored = colored(module_name, code)
local version_colored = colored(version, code)  -- 粗體黃色
if (mode() == "load") then
  local bar = string.rep("=", 72)
  LmodMessage(bar)
  LmodMessage(string.format("[MOD] Loaded %s tool: %s/%s", vendor, module_name_colored, version_colored))
  LmodMessage("Provider : ".. colored("Lin-Hung Lai", "33") .. " @ " .. colored("v1.0.1", "33") .. " - " .. colored("12 Sep 2025", "33"))  -- 36=cyan, 35=purple
  LmodMessage("Platform : ".. colored("Rocky Linux 8.10", "33"))
  LmodMessage(bar)
end

